/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package empresa.abc;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author HP PORTATIL
 */
public class Interfaz extends javax.swing.JFrame {

    private static EmpresaABC empresa = new EmpresaABC();
    
    private static DefaultListModel ModeloListaEntera = new DefaultListModel();
    private static DefaultListModel ModeloListaBonos = new DefaultListModel();
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        ListaEntera.setModel(ModeloListaEntera);
        ListaBonos.setModel(ModeloListaBonos);
    }

    public void RefrescarListaEntera(char c){
        String numerostring = fillBuscar.getText()+c;
        ArrayList<Integer> Indices = empresa.BuscarUsuario(Integer.parseInt(numerostring));
        
        ModeloListaEntera.removeAllElements();
        if(!(fillBuscar.getText()=="")){
            for(int i = 0 ; i<Indices.size() ; i++){
                int j = Indices.get(i);
                ModeloListaEntera.addElement("Rut: "+empresa.getRuts()[j]+"; Sueldo: "+empresa.getSueldos()[j]);
            }
        }
    }
    public void RefrescarListaEntera(){
        
        ArrayList<Integer> Indices;
        
        ModeloListaEntera.removeAllElements();
        if(fillBuscar.getText().length()<=1){
            for(int i = 0 ; i<empresa.getRuts().length ; i++){
                ModeloListaEntera.addElement("Rut: "+empresa.getRuts()[i]+"; Sueldo: "+empresa.getSueldos()[i]);
            }
        }else{
            String numerostring = fillBuscar.getText().substring(0, fillBuscar.getText().length()-1);
            Indices = empresa.BuscarUsuario(Integer.parseInt(numerostring));
            for(int i = 0 ; i<Indices.size() ; i++){
                int j = Indices.get(i);
                ModeloListaEntera.addElement("Rut: "+empresa.getRuts()[j]+"; Sueldo: "+empresa.getSueldos()[j]);
            }
        }
    }
    
    public void RefrescarListaBonos(){
        RegistroBono unicoBono = empresa.GenerarBono();
        int tamaño = unicoBono.getRuts().length;
        
        BonoMayor.setText("Rut: "+unicoBono.getRuts()[tamaño-1]+"; Aumento: "+unicoBono.getAumentos()[tamaño-1]);
        BonoMenor.setText("Rut: "+unicoBono.getRuts()[0]+"\n Aumento: "+unicoBono.getAumentos()[0]);
        
        ModeloListaBonos.removeAllElements();
        for(int i =0;i<tamaño;i++){
            ModeloListaBonos.addElement("Rut: "+unicoBono.getRuts()[i]+"; Aumento: "+unicoBono.getAumentos()[i]);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaEntera = new javax.swing.JList<>();
        fillBuscar = new javax.swing.JTextField();
        EnunBusRut = new javax.swing.JLabel();
        Error = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaBonos = new javax.swing.JList<>();
        EnunMayor = new javax.swing.JLabel();
        BonoMayor = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        EnunMenor = new javax.swing.JLabel();
        BonoMenor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(ListaEntera);

        fillBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillBuscarActionPerformed(evt);
            }
        });
        fillBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fillBuscarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fillBuscarKeyTyped(evt);
            }
        });

        EnunBusRut.setText("Buscar RUT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(Error, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(fillBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(EnunBusRut)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(EnunBusRut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fillBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Error, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Saldos", jPanel1);

        jScrollPane2.setViewportView(ListaBonos);

        EnunMayor.setText("Mayor Bono");

        jButton1.setText("Crear bono");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        EnunMenor.setText("Menor bono");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnunMayor)
                    .addComponent(BonoMayor)
                    .addComponent(jButton1)
                    .addComponent(EnunMenor)
                    .addComponent(BonoMenor))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(EnunMayor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BonoMayor)
                .addGap(43, 43, 43)
                .addComponent(EnunMenor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BonoMenor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(51, 51, 51))
        );

        jTabbedPane1.addTab("Bonos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fillBuscarKeyTyped
        char i = evt.getKeyChar();
        
        if (!Character.isDigit(i) || fillBuscar.getText().length()==6){
            evt.consume();
        }else{
            RefrescarListaEntera(i);
        }
        
        
    }//GEN-LAST:event_fillBuscarKeyTyped

    private void fillBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fillBuscarKeyPressed
        char i = evt.getKeyChar();
        
        if (i=='\b'){
            RefrescarListaEntera();
        }
    }//GEN-LAST:event_fillBuscarKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        RefrescarListaBonos();
        
        this.jButton1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fillBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fillBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        for(int i = 0 ; i<empresa.getRuts().length ; i++){
                ModeloListaEntera.addElement("Rut: "+empresa.getRuts()[i]+"; Sueldo: "+empresa.getSueldos()[i]);
            }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BonoMayor;
    private javax.swing.JLabel BonoMenor;
    private javax.swing.JLabel EnunBusRut;
    private javax.swing.JLabel EnunMayor;
    private javax.swing.JLabel EnunMenor;
    private javax.swing.JLabel Error;
    private javax.swing.JList<String> ListaBonos;
    private javax.swing.JList<String> ListaEntera;
    private javax.swing.JTextField fillBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
